server:
  port: 8123
spring:
      datasource:
          name: zhiren
          url: jdbc:mysql://192.168.253.128:3306/zhiren?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: 123456
          # 使用druid数据源
          platform: mysql
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat,wall,log4j
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: zhiren.model
#pagehelper分页插件
pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql